### ISSUE TITLE
PATH not changed.

### ISSUE THREAD

**Issue by eggbean** [therootcompany/pathman#3]
Whenever I try adding to `%PATH%` using this I just get this error:

```
C:\Users\jason\winfiles\bin>pathman add C:\Users\jason\winfiles\bin
PATH not changed.

C:\Users\jason\winfiles\bin>pathman add "C:\Users\jason\winfiles\bin"
PATH not changed.
```

Why isn't it working?

**Comment by coolaj86** [comment]
It's already in your PATH in the Windows registry. It's not an error, there's just nothing more to do.

As soon as you close and reopen your terminal it should take effect.

In some cases you may need to reboot, but that shouldn't be required. If it is, there may be something else wrong.

Make sure you don't "run as administrator" though. That won't update the correct PATH.

**Comment by eggbean** [comment]
Thanks for your help, but I could not get it working. It's not a big problem for me though, as I have realised that it would be easier to add to %PATH% in a startup script. Cheers.

**Comment by chipbite** [comment]
So if I (A) run `pathman add` as user in windows, user env path (Path at `HKCU\Environment`) gets added to, but if I (B) run `pathman add` as admin it updates system path (at `HKLM\System\CurrentControlSet\Control\Session Manager\Environment\` ) - correct?

**Comment by chipbite** [comment]
@coolaj86 - I ran as normal user and then admin just now, and pathman add does the same thing in both cases, it modifies user env path (A in my comment above).

Was the idea for it to do B or?
